# Generated by Django 5.0.6 on 2024-05-22 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAE_GA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('duree', models.TimeField()),
                ('groupe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SAE_GA.groupe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAE_GA.enseignant')),
            ],
        ),
    ]
