# Generated by Django 5.0.6 on 2024-05-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAE_GA', '0002_enseignant_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('groupe', models.CharField(max_length=100)),
                ('photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
