# Generated by Django 5.0.6 on 2024-05-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAE_GA', '0003_etudiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.CharField(max_length=100)),
                ('cours', models.CharField(max_length=100)),
                ('accepte', models.BooleanField()),
                ('justification', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cours',
            name='enseignant',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cours',
            name='groupe',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
