# Generated by Django 5.0.6 on 2024-05-28 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAE_GA', '0004_absence_alter_cours_enseignant_alter_cours_groupe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='groupe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SAE_GA.groupe'),
        ),
    ]
